CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, username text NOT NULL, username_normalized text NOT NULL UNIQUE, password_hash text NOT NULL, password_salt text NOT NULL, created_at text NOT NULL, updated_at text NOT NULL);
CREATE TABLE IF NOT EXISTS auth_tokens (token_hash text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at text NOT NULL, expires_at text NOT NULL, last_used_at text NOT NULL);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_user_id ON auth_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_expires_at ON auth_tokens(expires_at);
CREATE TABLE IF NOT EXISTS schema_metadata (key text PRIMARY KEY, value text NOT NULL);
CREATE TABLE IF NOT EXISTS stock_analyses (id text PRIMARY KEY, stock_id text NOT NULL, status text NOT NULL CHECK (status IN ('analyzing','completed','failed')), input_json jsonb NOT NULL, analysis_json jsonb, error text, created_at text NOT NULL, updated_at text NOT NULL);
CREATE INDEX IF NOT EXISTS idx_stock_analyses_stock_created ON stock_analyses(stock_id, created_at DESC);
CREATE TABLE IF NOT EXISTS chat_messages (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, request_id text NOT NULL, role text NOT NULL CHECK (role IN ('user','assistant')), contents_json jsonb NOT NULL, status text NOT NULL CHECK (status IN ('pending','completed','failed')), created_at text NOT NULL, updated_at text NOT NULL, UNIQUE(user_id, request_id, role));
CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id ON chat_messages(user_id, id);
