source 'https://cdn.cocoapods.org/'

target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'OpenKuiklyIOSRender', :git => 'https://github.com/Tencent-TDS/KuiklyUI.git', :tag => '2.25.0'
  pod 'shared', :path => '../shared'

  pod 'SDWebImage'
  pod 'SVGKit'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    next unless target.name == 'SVGKit'

    target.build_configurations.each do |configuration|
      configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
    end
  end
end
